export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';

export const GET_TIME_SLOT="GET_TIME_SLOT";
export const GET_TIME_SLOT_SUCCESS = 'GET_TIME_SLOT_SUCCESS';
export const GET_TIME_SLOT_ERROR = 'GET_TIME_SLOT_ERROR';
export const GET_TIME_SLOTS_BY_DATE = 'GET_TIME_SLOTS_BY_DATE';